//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sach_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioHang
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> IDDonHag { get; set; }
        public Nullable<System.Guid> sachid { get; set; }
        public Nullable<decimal> TamTinh { get; set; }
        public Nullable<int> soluong { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
